/**
 * Shared audit contracts for every APMS engine.
 *
 * The Audit Layer is responsible for explaining what Pin&Go did,
 * why it did it, and whether the operation moved the property closer
 * to autonomous execution.
 */

export type AuditStatus = "SUCCESS" | "FAILED" | "SKIPPED";

export type AuditSeverity = "INFO" | "WARNING" | "CRITICAL";

export type AuditEntityType =
  | "PROPERTY"
  | "RESERVATION"
  | "REVENUE"
  | "ACCESS"
  | "CLEANING"
  | "MESSAGING"
  | "PAYMENT"
  | "DISTRIBUTION"
  | "SYSTEM";

export type AuditEventType =
  | "DECISION_CREATED"
  | "DECISION_APPLIED"
  | "DECISION_SKIPPED"
  | "ACTION_STARTED"
  | "ACTION_COMPLETED"
  | "ACTION_FAILED"
  | "SYNC_STARTED"
  | "SYNC_COMPLETED"
  | "SYNC_FAILED";

export interface AuditDecisionTrace {
  /**
   * Engine that produced the decision.
   * Example: Revenue, Access, Cleaning, Messaging.
   */
  engine: string;

  /**
   * Rule or decision identifier.
   * Example: SEASONAL_RULE, MINIMUM_NIGHTLY_RATE, ACCESS_GRANT_CREATED.
   */
  rule: string;

  /**
   * Human-readable label.
   */
  label: string;

  /**
   * Previous value before the decision.
   */
  previousValue?: unknown;

  /**
   * New value after the decision.
   */
  newValue?: unknown;

  /**
   * Absolute change when applicable.
   */
  adjustment?: number | null;

  /**
   * Percentage change when applicable.
   */
  adjustmentPercent?: number | null;

  /**
   * Whether the decision actually changed something.
   */
  applied: boolean;

  /**
   * Optional confidence score from 0 to 100.
   */
  confidence?: number;

  /**
   * Additional engine-specific details.
   */
  metadata?: Record<string, unknown>;
}

export interface AuditEntry {
  /**
   * Engine that executed.
   */
  engine: string;

  /**
   * Decision identifier.
   */
  decisionId: string;

  /**
   * Entity being audited.
   */
  entityType?: AuditEntityType;

  /**
   * Entity id being audited.
   */
  entityId?: string;

  /**
   * Event type generated by the engine.
   */
  eventType?: AuditEventType;

  /**
   * Execution result.
   */
  status: AuditStatus;

  /**
   * Audit severity.
   */
  severity?: AuditSeverity;

  /**
   * Short human-readable summary.
   */
  summary?: string;

  /**
   * UTC timestamps.
   */
  startedAt: Date;

  completedAt: Date;

  /**
   * Execution duration.
   */
  durationMs: number;

  /**
   * Optional explanation.
   */
  reason?: string;

  /**
   * Structured decisions produced by the engine.
   */
  decisions?: AuditDecisionTrace[];

  /**
   * Optional recommended next action.
   */
  recommendedAction?: string;

  /**
   * Engine metadata.
   */
  metadata?: Record<string, unknown>;
}

export interface AuditTimeline {
  /**
   * Reservation, Property, Access, etc.
   */
  entityId: string;

  /**
   * Entity type for this timeline.
   */
  entityType?: AuditEntityType;

  entries: AuditEntry[];
}