import { CHANNEX_CERTIFICATION_V1_MANIFEST } from "./channex-certification-v1.fixture";
import {
  certifyChannexBookingReceivingScenario,
} from "./channex-certification-booking-receiving.policy";

const base = {
  manifest: CHANNEX_CERTIFICATION_V1_MANIFEST,
  executionMode: "LOCAL_CONTRACT_ONLY" as const,
  realChannexCallsAllowed: false as const,
};

export const CHANNEX_CERTIFICATION_V1_SCENARIOS = Object.freeze([
  {
    ...base,
    id: 1,
    name: "Full Data Update",
    expected: {
      availabilityRequests: 1,
      restrictionsRequests: 1,
      availabilityEndpoint: "/api/v1/availability",
      restrictionsEndpoint: "/api/v1/restrictions",
      horizonDays: 500,
      syncMode: "FULL",
    },
  },
  {
    ...base,
    id: 2,
    name: "Single Date Update for Single Rate",
    expected: {
      endpoint: "/api/v1/restrictions",
      requestCount: 1,
      date: "2026-11-22",
      rateMinorUnits: 33300,
      requiredFields: ["rate"],
      forbiddenFields: [
        "min_stay_arrival",
        "min_stay_through",
        "max_stay",
        "stop_sell",
        "closed_to_arrival",
        "closed_to_departure",
      ],
      ratePlanId: CHANNEX_CERTIFICATION_V1_MANIFEST.channexRatePlanId,
    },
  },
  {
    ...base,
    id: 3,
    name: "Single Date Update for Multiple Rates",
    expected: {
      status: "SKIPPED",
      reason: "CHANNEX_EMAIL_ACCEPTED_SINGLE_RATE_PLAN_OMISSION",
    },
  },
  {
    ...base,
    id: 4,
    name: "Multiple Date Update",
    expected: {
      endpoint: "/api/v1/restrictions",
      requestCount: 1,
      dateFrom: "2026-11-01",
      dateTo: "2026-11-10",
      dateToInclusive: true,
      rateMinorUnits: 24100,
      requiredFields: ["rate"],
      ratePlanId: CHANNEX_CERTIFICATION_V1_MANIFEST.channexRatePlanId,
    },
  },
  {
    ...base,
    id: 5,
    name: "Min Stay Update",
    expected: {
      endpoint: "/api/v1/restrictions",
      requestCount: 1,
      date: "2026-11-23",
      minStay: 3,
      requiredFields: ["min_stay_arrival", "min_stay_through"],
      forbiddenFields: [
        "rate",
        "max_stay",
        "stop_sell",
        "closed_to_arrival",
        "closed_to_departure",
      ],
      ratePlanId: CHANNEX_CERTIFICATION_V1_MANIFEST.channexRatePlanId,
    },
  },
  {
    ...base,
    id: 6,
    name: "Stop Sell Update",
    expected: {
      status: "SKIPPED",
      reason: "STOP_SELL_NOT_SUPPORTED",
    },
  },
  {
    ...base,
    id: 7,
    name: "Multiple Restrictions Update",
    expected: {
      endpoint: "/api/v1/restrictions",
      requestCount: 1,
      dateFrom: "2026-11-01",
      dateTo: "2026-11-10",
      dateToInclusive: true,
      minStay: 1,
      maxStay: 4,
      requiredFields: [
        "min_stay_arrival",
        "min_stay_through",
        "max_stay",
      ],
      forbiddenFields: [
        "rate",
        "stop_sell",
        "closed_to_arrival",
        "closed_to_departure",
      ],
      ratePlanId: CHANNEX_CERTIFICATION_V1_MANIFEST.channexRatePlanId,
    },
  },
  {
    ...base,
    id: 8,
    name: "Half-year Update",
    expected: {
      endpoint: "/api/v1/restrictions",
      requestCount: 1,
      dateFrom: "2026-12-01",
      dateTo: "2027-05-01",
      dateToInclusive: true,
      rateMinorUnits: 43200,
      minStay: 2,
      requiredFields: ["rate", "min_stay_arrival", "min_stay_through"],
      ratePlanId: CHANNEX_CERTIFICATION_V1_MANIFEST.channexRatePlanId,
    },
  },
  {
    ...base,
    id: 9,
    name: "Single Date Availability Update",
    expected: {
      endpoint: "/api/v1/availability",
      requestCount: 1,
      syntax: "DATE",
      date: "2026-11-21",
      availability: 1,
      roomTypeId: CHANNEX_CERTIFICATION_V1_MANIFEST.channexRoomTypeId,
    },
  },
  {
    ...base,
    id: 10,
    name: "Multiple Date Availability Update",
    expected: {
      endpoint: "/api/v1/availability",
      requestCount: 1,
      syntax: "DATE_RANGE",
      dateFrom: "2026-11-10",
      dateTo: "2026-11-16",
      dateToInclusive: true,
      availability: 1,
      mergedSequences: true,
      roomTypeId: CHANNEX_CERTIFICATION_V1_MANIFEST.channexRoomTypeId,
    },
  },
  {
    ...base,
    id: 11,
    name: "Booking Receiving",
    localGate: certifyChannexBookingReceivingScenario,
    expected: {
      lifecycle: ["NEW", "MODIFICATION", "CANCELLATION"],
      rejectedCertificationRevisionIds: [
        "640268f5-9d5c-471e-93bc-53ddd93dabd0",
        "cbbeb9f0-6923-4139-8b48-4077e96143f9",
        "e3b6545e-edba-4148-93ec-d18de02eaf5e",
      ],
      permittedIngestMechanisms: [
        "BOOKING_REVISION_BY_ID",
        "BOOKING_REVISION_FEED",
      ],
      forbiddenIngestMechanisms: [
        "BOOKING_LIST",
        "BOOKING_LIST_POLLING",
        "BOOKING_FIND",
        "BOOKING_BY_ID",
        "BOOKING_RECEIVED_VIA_BOOKING_FIND",
        "MANUAL_PERSIST_AND_ACK",
      ],
      revisionEndpoints: [
        "/api/v1/booking_revisions/:id",
        "/api/v1/booking_revisions/feed",
      ],
      acknowledgeEndpoint: "/api/v1/booking_revisions/:id/ack",
      persistBeforeAck: true,
      sameReservationIdentity: true,
      duplicatesAllowed: false,
      webhookHttpStatusMin: 200,
      webhookHttpStatusMax: 299,
      webhookDeliveryNotesSuccessRequired: true,
      eventStatus: "PROCESSED",
      persistenceStatus: "SUCCESS",
      acknowledgementStatus: "SUCCESS",
      bookingFindEventsExpected: 0,
    },
  },
  {
    ...base,
    id: 12,
    name: "Rate Limits",
    expected: {
      restrictionsPerMinute: 10,
      availabilityPerMinute: 10,
      ariTotalPerMinute: 20,
      queueRequired: true,
      batchingRequired: true,
      exponentialBackoffRequired: true,
      pauseAfterErrorMs: 60000,
    },
  },
  {
    ...base,
    id: 13,
    name: "Update Logic",
    expected: {
      deltaUpdatesRequired: true,
      timerBasedFullSyncAllowed: false,
      fullSyncMinimumIntervalHours: 24,
    },
  },
] as const);
